version: '3.7'

services:
  db:
    image: postgres:12.5-alpine
    ports:
      - 27888:5432
    expose: 
      - "5432"
    volumes:
        - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=crowdsourcing_db
      - POSTGRES_USER=crowdsourcing_user
    restart: unless-stopped
  
  redis:
    image: redis:5-alpine
    ports:
        - 32678:6379
    expose: 
        - "6379"
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
  
  cache:
    image: memcached:1.6.9-alpine
    ports:
      - 27887:11211
    expose:
      - "11211"
    entrypoint:
      - memcached
      - -m 64
    volumes:
      - ./memcached_data:/usr/local/etc/memcached_data
    restart: unless-stopped
  
  minio:
    image: minio/minio
    ports: 
      - 9000:9000
    expose:
      - "9000"
    volumes:
      - ./mnt/data:/minio_data
    environment:
      - MINIO_ACCESS_KEY=test!crowdsourcing_minio
      - MINIO_SECRET_KEY=secret!crowdsourcing_minio
    command: server /data
    depends_on:
      - db
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    env_file: 
      - ".env"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - cache
      - minio